excluded:
- Pods
- Register
- Frameworks
- Dependencies

disabled_rules:
- multiple_closures_with_trailing_closure

trailing_whitespace:
  ignores_empty_lines: true
vertical_whitespace:
  max_empty_lines: 2
line_length:
  warning: 180
  ignores_urls: true
  ignores_interpolated_strings: true
large_tuple:
  warning: 3
  error: 4
identifier_name:
  max_length:
   warning: 60
  min_length:
    warning: 1
    error: 1
  allowed_symbols: ["_"]
type_name:
  allowed_symbols: ["_"]
  max_length:
    warning: 50
